---
title: "Reproducible Research"
author: "Osiepere"
date: "2019 M01 28"
output: html_document
---

```{r}
acti_data <- read.csv("activity.csv")
summary(acti_data)
```

```{r}
head(acti_data)
```

```{r}
steps <- aggregate(acti_data$steps, by = list(Date = acti_data$date), FUN = sum)
library(ggplot2)
names(steps)[names(steps) == "x"] <- "Total"
temp <- as.Date(steps$Date, "%Y-%m-%d")
steps$Date <- format(temp, format = "%m-%d")
head(steps)
```

```{r}
hist1 <- ggplot(data = na.omit(steps), aes(Total)) + 
    geom_histogram(binwidth = 1500, colour = "white") +
    xlab("Total Number of Steps Taken Each Day") +
    ylab("Count") +
    ggtitle("Histogram of the Total Number of Steps Taken Each Day")
print(hist1)
```


```{r}
mean(na.omit(steps$Total))
```

```{r}
median(na.omit(steps$Total))
```

```{r}
five_min_steps <- aggregate(steps ~ interval, data = acti_data, FUN =mean)
TimeSeries1 <- ggplot(data = five_min_steps, aes(x = interval, y = steps)) + 
    geom_line() +
    xlab("Time Intervals (5 Minutes is an unit)") + 
    ylab("Total Number of Steps") +
    ggtitle("Average Number of Steps Taken of the 5-Minute Interval")
print(TimeSeries1)
```

```{r}
head(five_min_steps)
```

```{r}
five_min_steps[which(five_min_steps$steps == max(five_min_steps$steps)),]
```

```{r}
sapply(X = acti_data, FUN = function(x) sum(is.na(x)))
```

```{r}
library(dplyr)
```

```{r}
replace_with_mean <- function(num) replace(num, is.na(num), mean(num, na.rm = TRUE))
meanday <- (acti_data %>% group_by(interval) %>% mutate(steps = replace_with_mean(steps)))
head(meanday)
```

```{r}
sum(is.na(meanday))
```

```{r}
new_dataset <- as.data.frame(meanday)
head(new_dataset)
```

```{r}
summary(new_dataset)
```

```{r}
new_steps <- aggregate(new_dataset$steps, by = list(new_dataset$date), FUN = sum)
names(new_steps)[names(new_steps) == "x"] <- "Total"
names(new_steps)[names(new_steps) == "Group.1"] <- "Date"
hist2 <- ggplot(data = new_steps, aes(Total)) + 
    geom_histogram(binwidth = 1500, colour = "white") +
    xlab("Total Number of Steps Taken Each Day") +
    ylab("Count") +
    ggtitle("Histogram of the Total Number of Steps Taken Each Day with New Version Dataset")
print(hist2)
```

```{r}
library(grid)
library(gridExtra)
```

```{r}
grid.arrange(hist1, hist2, ncol = 2)
```

```{r}
mean(na.omit(steps$Total))
```

```{r}
median(na.omit(steps$Total))
```

```{r}
mean(new_steps$Total)
```

```{r}
median(new_steps$Total)
```

```{r}
new_dataset$WeekendOrWeekday <- ifelse(weekdays(as.Date(new_dataset$date)) %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"), "Weekday", "Weekend")
head(new_dataset)
```

```{r}
new_dataset <- (new_dataset %>% group_by(interval, WeekendOrWeekday) %>% summarise(Mean = mean(steps)))
ggplot(new_dataset, mapping = aes(x = interval, y = Mean)) + geom_line() +
    facet_grid(WeekendOrWeekday ~.) + xlab("Interval") + ylab("Mean of Steps") +
    ggtitle("Comparison of Average Number of Steps in Each Interval")
```

There are differences in activity patterns between weekdays and weekends. Compared with weekdays, during weekends, people tend to get up late and stay up late. On weekends, people tend to be more active, since their steps are not stable caused of not working.
































